# Generated by Django 3.1.4 on 2022-04-17 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Clients',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_name', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=64)),
                ('phone', models.CharField(max_length=32)),
                ('course', models.CharField(max_length=20)),
            ],
        ),
    ]
