# Generated by Django 3.1.4 on 2022-04-18 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_client_certificate'),
    ]

    operations = [
        migrations.AddField(
            model_name='client_certificate',
            name='qr_code',
            field=models.ImageField(blank=True, upload_to='qr_codes'),
        ),
    ]
